### ISSUE TITLE
Social meta chores

### ISSUE THREAD

**Issue by argyleink** [argyleink/gui-challenges#12]
- [ ] social for this repo
- [ ] social img for each post
- [ ] social template (and/or is use in each post)

**Comment by argyleink** [comment]
related to #86
